### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by guirar** [cleitonleonel/follower#1]
Está dando KeyError: 0 quando mudo para false o "is_demo".
No modo demo funciona corretamente, faz as entradas do canal Bot Million, porém no real da erro.

**Comment by cleitonleonel** [comment]
![image](https://user-images.githubusercontent.com/11451914/194648676-d01029c6-c50d-42ec-a6c1-8f2ad67707aa.png)

**Comment by guirar** [comment]
Entrei em contato.
